### ISSUE TITLE
Unable to debug actions created via browser

### ISSUE THREAD

**Issue by VidyasagarMSC** [openwhisk/openwhisk-debugger#22]
I am seeing this error - 

> Error: entity does not exist while in this operation:  looking up action

While trying to Attach an action created via Browser using OpenWhisk Debugger (wskdb). 

Action created via CLI works as expected without any error.

**Comment by ScottChapman** [comment]
I see that if my action name has a space in it.

**Comment by thvmm** [comment]
If you publish your action whitin a space, such: myspace/myaction

When you list your actions on wskdb you get only the action name whitout the space, but to attach you need to inform the published name:

attach myspace/myaction

instead of

attach myaction

**Comment by ScottChapman** [comment]
That doesn't fix my issue. I always seem to get an error if I include my space (org_space from bluemix) but it does seem to work if I just use action.

I still have issue #24 though

**Comment by starpit** [comment]
my apologies for the delays in getting on this. i hope to get the debugger back on track over the next few days!

**Comment by ScottChapman** [comment]
Let me know if I can help!

**Comment by starpit** [comment]
@VidyasagarMSC we just merged in a PR. it's possible that your issue is resolved. when you get a chance, would you be able to see if this is true? thanks!

**Comment by ScottChapman** [comment]
To it does appear to attach ok now. I at least get the prompt back, and I can see from the list that I am attached.

But... browser-based debugger doesn't launch when action is triggered via the cloud.

**Comment by starpit** [comment]
a PR is under review #27
