### ISSUE TITLE
Invoke <action> just hangs

### ISSUE THREAD

**Issue by ScottChapman** [openwhisk/openwhisk-debugger#24]
I have a very simple hello world action. I can attach to it, but nothing happens when I try to invoke it:

> Scotts-MacBook-Pro:openwisk scottchapman$ wskdb MyTest
> Welcome to the OpenWhisk Debugger
> 
> Attaching to MyTest
>    Creating action trampoline
> ok
> (wskdb) invoke MyTest
>

**Comment by ScottChapman** [comment]
I found this in the logs for the failed action that the debugger appeared to create:
```
"logs": [
    "2017-03-23T20:20:19.100443569Z stdout: Invoking { action: 'MyTest',",
    "2017-03-23T20:20:19.10051187Z  stdout: namespace: '_',",
    "2017-03-23T20:20:19.100520558Z stdout: broker: 'https://owdbg-broker.mybluemix.net',",
    "2017-03-23T20:20:19.100528133Z stdout: onDone_trigger: '___debug___continuation-trigger-7500a22a-3f55-474f-8d02-3486bed6eac9' }",
    "2017-03-23T20:20:19.100537641Z stdout: A",
    "2017-03-23T20:20:19.10272564Z  stderr: ReferenceError: whisk is not defined",
    "2017-03-23T20:20:19.102744849Z stderr: at eval (eval at <anonymous> (/nodejsAction/runner.js:75:109), <anonymous>:42:8)",
    "2017-03-23T20:20:19.102752649Z stderr: at NodeActionRunner.main [as userScriptMain] (eval at <anonymous> (/nodejsAction/runner.js:75:109), <anonymous>:20:12)",
    "2017-03-23T20:20:19.102758793Z stderr: at /nodejsAction/runner.js:94:45",
    "2017-03-23T20:20:19.102764645Z stderr: at NodeActionRunner.run (/nodejsAction/runner.js:88:16)",
    "2017-03-23T20:20:19.10277013Z  stderr: at doRun (/nodejsAction/src/service.js:154:31)",
    "2017-03-23T20:20:19.102775387Z stderr: at runCode (/nodejsAction/src/service.js:110:20)",
    "2017-03-23T20:20:19.102780553Z stderr: at /nodejsAction/app.js:61:13",
    "2017-03-23T20:20:19.102792191Z stderr: at Layer.handle [as handle_request] (/nodejsAction/node_modules/express/lib/router/layer.js:95:5)",
    "2017-03-23T20:20:19.102797787Z stderr: at next (/nodejsAction/node_modules/express/lib/router/route.js:131:13)",
    "2017-03-23T20:20:19.102803124Z stderr: at Route.dispatch (/nodejsAction/node_modules/express/lib/router/route.js:112:3)"
```

**Comment by rabbah** [comment]
Hmm. The whisk object no longer exists. Code needs to make use of npm openwhisk instead.

**Comment by ScottChapman** [comment]
I was going to take a gander at it tomorrow but I think it is out of my wheelhouse. This something you can address?

**Comment by rabbah** [comment]
There are two references that need to change:
https://github.com/openwhisk/openwhisk-debugger/blob/master/invoker/owdbg-invoker.js#L42
https://github.com/openwhisk/openwhisk-debugger/blob/master/invoker/owdbg-invoker.js#L72

`whisk.getAuthKey` should be changed to `process.env.$__OW_AUTH_KEY`.

**Comment by ScottChapman** [comment]
I made both those changes to my locally installed version and it didn't have any effect.

I do see two actions get created; both are named "__debug__ ..." so I think the credential handling looks OK.
