### ISSUE TITLE
Will not install

### ISSUE THREAD

**Issue by javastl** [openwhisk/openwhisk-debugger#25]
I hope you are able to help me.  The  install of the OpenWhisk debugger has failed. I attaching the log

Pete
[npm-debug.zip](https://github.com/openwhisk/openwhisk-debugger/files/906459/npm-debug.zip)

**Comment by starpit** [comment]
Thanks for the info. We will investigate this issue today!

**Comment by starpit** [comment]
i think i see now. the postinstall script currently assumes unix-isms. i'll get a PR ready for this!

**Comment by starpit** [comment]
also, @javastl you will, for now, need to downgrade to node 6.2.0, while we work on a fix for more recent versions of node.

(background: node 6.3.0 more or less broke node-inspector, in favor of their own home-grown solution: https://github.com/node-inspector/node-inspector/issues/905)
